services:
  api:
    container_name: catalog-api
    build:
      context: ./ # Utilisez le chemin relatif pour le contexte
      dockerfile: Dockerfile 
    ports:
      - "8080:80"  # Expose le port 8080 de l'hôte vers le port 80 du conteneur
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      retries: 5

  db:
    container_name: catalog-db
    build:
      context: ./sql-scripts # Contexte relatif vers votre dossier sql-scripts
    ports:
      - "4444:3306"  # Expose le port de la base de données
    networks:
      - mynetwork

  server:
    container_name: catalog-server-nginx
    build:
      context: ./nginx # Contexte relatif vers votre dossier Nginx
    ports:
      - "8081:8080"  # Expose Nginx sur le port 8081
    depends_on:
      - api
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


